config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"
    
      get 'welcome/about'
      get 'welcome/terms'

resources :trips

end

app/models/trip.rb
class Trip < ActiveRecord::Base

  LOCATION1 = %w(Tribeca)
  validates :location1, inclusion: { in: LOCATION1 }

  LOCATION2 = %w(Gramercy)
  validates :location2, inclusion: { in: LOCATION2 }

  PLACE = %w(Bar Coffee Restaurant)
  validates :place, inclusion: { in: PLACE }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]


  def index
    @trips = Trip.all
  end

  def show


  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_trip
      @trip = Trip.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:location1, :location2, :place, :latitude, :longitude)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

def about
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flashes.html.erb
<div>
<% flash.each do |key, value| %>
   <div>
   <br> <br>
   <a href="#" data-dismiss="alert" style="margin-left: 90%;">X 
   <%= content_tag(:p, value, :class => "flash #{key}") %> </a>
    </div>
<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Between Us</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/welcome/about">About</a></li>
        <li><a href="/welcome/terms">Terms</a></li>
        <li><a href="/contact">Contact</a></li>        <li class="dropdown">
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Meetup</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '#' %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">

  <%= render "layouts/flashes" %>
  
  <div id="container">

<%= yield %>
	
	<%= render "layouts/footer" %>

</body>

</html>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="background-for-form">
</div>

<br>

<div class="form-styles">
    <form class="form-inline" role="form">  
    <div class="form-group">
      <%= f.label :Your_Neighborhood? %><br>
      <%= f.select :location1, Trip::LOCATION1, prompt: "Choose Your Neighborhood" %>
    </div>
    <div class="form-group">
      <%= f.label :Their_Neighborhood? %><br>
      <%= f.select :location2, Trip::LOCATION2, prompt: "Choose Their Neighborhood" %>
    </div>
    <div class="form-group">
      <%= f.label :What_Type_of_Place? %><br>
      <%= f.select :place, Trip::PLACE, prompt: "Choose a type of location" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Let's Go!", :class => 'btn btn-lg' %>
    </div>
  </form>
</div>

<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<article>
  <header>
    <h1 style="text-align: center;"> Listing All Meetups  </h1> 
  </header>
</article>

<table class="table table-bordered" id="users" style = "width: 85%; margin-top: 50px;" align="center">
  <thead>
    <tr>
      <th>ID</th>
      <th>Created On</th>
      <th>My Neighborhood</th>
      <th>Their Neighborhood</th>
      <th>Type Of Place</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.id %></td>
        <td><%= trip.created_at %></td>
        <td><%= trip.location1 %></td>
        <td><%= trip.location2 %></td>
        <td><%= trip.place %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Meetup', new_trip_path %>

app/views/trips/new.html.erb
<h1 style="color: #FFD700;">Find Places We can Meet!</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<article>
  <header>
    <h1 style="text-align: center;"> My Meetup </h1> 
  </header>
</article>


<table class="table table-bordered" id="users" style = "width: 85%; margin-top: 50px;" align="center">

  <thead>
    <tr>
      <th>My Neighborhood</th>
      <th>Their Neighborhood</th>
      <th>Type Of Place</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @trip.location1 %></td>
        <td><%= @trip.location2 %></td>
        <td><%= @trip.place %></td>
      </tr>
  </tbody>

</table>

<%= link_to 'New Meetup', new_trip_path %>
<%= link_to 'Edit Meetup', edit_trip_path(@trip) %> 
<%= link_to 'Back', trips_path %>

app/views/welcome/about.html.erb
About

app/views/welcome/index.html.erb
<h1 style="text-align: center;">Find Somewhere To Meet Between Two Places</h1>

<div style="text-align:center;">

<a href="/trips/new" class="btn btn-primary" role="button" style="background-color: black;
color: rgb(0, 197, 255);">New Meetup</a>

</div>

app/views/welcome/terms.html.erb
Terms